title = "Configuration File"

[common_parameters]
problem_type = "classification"
train_val_split = 0.75 # 75% of samples in the training set, 25% in the validation Settings
variables = ["Exposed_YN", "Age","Sex", "LLatVent",	"RLatVent",	"Lthal", "Rthal",	"Lcaud",	"Rcaud",	"Lput",	"Rput",	"Lpal",	"Rpal",	"Lhippo",	"Rhippo",	"Lamyg", "Ramyg",	"Laccumb",	"Raccumb",	"L_bankssts_thickavg",	"L_caudalanteriorcingulate_thickavg",	"L_caudalmiddlefrontal_thickavg",	"L_cuneus_thickavg",	"L_entorhil_thickavg",	"L_fusiform_thickavg",	"L_inferiorparietal_thickavg",	"L_inferiortemporal_thickavg",	"L_isthmuscingulate_thickavg",	"L_lateraloccipital_thickavg",	"L_lateralorbitofrontal_thickavg",	"L_lingual_thickavg",	"L_medialorbitofrontal_thickavg",	"L_middletemporal_thickavg",	"L_parahippocampal_thickavg",	"L_paracentral_thickavg",	"L_parsopercularis_thickavg",	"L_parsorbitalis_thickavg",	"L_parstriangularis_thickavg",	"L_pericalcarine_thickavg",	"L_postcentral_thickavg",	"L_posteriorcingulate_thickavg",	"L_precentral_thickavg",	"L_precuneus_thickavg",	"L_rostralanteriorcingulate_thickavg",	"L_rostralmiddlefrontal_thickavg",	"L_superiorfrontal_thickavg",	"L_superiorparietal_thickavg",	"L_superiortemporal_thickavg",	"L_supramargil_thickavg",	"L_frontalpole_thickavg",	"L_temporalpole_thickavg",	"L_transversetemporal_thickavg",	"L_insula_thickavg",	"R_bankssts_thickavg",	"R_caudalanteriorcingulate_thickavg",	"R_caudalmiddlefrontal_thickavg",	"R_cuneus_thickavg",	"R_entorhil_thickavg",	"R_fusiform_thickavg",	"R_inferiorparietal_thickavg",	"R_inferiortemporal_thickavg",	"R_isthmuscingulate_thickavg",	"R_lateraloccipital_thickavg",	"R_lateralorbitofrontal_thickavg",	"R_lingual_thickavg",	"R_medialorbitofrontal_thickavg",	"R_middletemporal_thickavg",	"R_parahippocampal_thickavg",	"R_paracentral_thickavg",	"R_parsopercularis_thickavg",	"R_parsorbitalis_thickavg",	"R_parstriangularis_thickavg",	"R_pericalcarine_thickavg",	"R_postcentral_thickavg",	"R_posteriorcingulate_thickavg",	"R_precentral_thickavg",	"R_precuneus_thickavg",	"R_rostralanteriorcingulate_thickavg",	"R_rostralmiddlefrontal_thickavg",	"R_superiorfrontal_thickavg",	"R_superiorparietal_thickavg",	"R_superiortemporal_thickavg",	"R_supramargil_thickavg",	"R_frontalpole_thickavg",	"R_temporalpole_thickavg",	"R_transversetemporal_thickavg",	"R_insula_thickavg",	"L_bankssts_surfavg",	"L_caudalanteriorcingulate_surfavg",	"L_caudalmiddlefrontal_surfavg",	"L_cuneus_surfavg",	"L_entorhil_surfavg",	"L_fusiform_surfavg",	"L_inferiorparietal_surfavg",	"L_inferiortemporal_surfavg",	"L_isthmuscingulate_surfavg",	"L_lateraloccipital_surfavg",	"L_lateralorbitofrontal_surfavg",	"L_lingual_surfavg",	"L_medialorbitofrontal_surfavg",	"L_middletemporal_surfavg",	"L_parahippocampal_surfavg",	"L_paracentral_surfavg",	"L_parsopercularis_surfavg",	"L_parsorbitalis_surfavg",	"L_parstriangularis_surfavg",	"L_pericalcarine_surfavg",	"L_postcentral_surfavg",	"L_posteriorcingulate_surfavg",	"L_precentral_surfavg",	"L_precuneus_surfavg",	"L_rostralanteriorcingulate_surfavg",	"L_rostralmiddlefrontal_surfavg",	"L_superiorfrontal_surfavg",	"L_superiorparietal_surfavg",	"L_superiortemporal_surfavg",	"L_supramargil_surfavg",	"L_frontalpole_surfavg",	"L_temporalpole_surfavg",	"L_transversetemporal_surfavg",	"L_insula_surfavg",	"R_bankssts_surfavg",	"R_caudalanteriorcingulate_surfavg",	"R_caudalmiddlefrontal_surfavg",	"R_cuneus_surfavg",	"R_entorhil_surfavg",	"R_fusiform_surfavg",	"R_inferiorparietal_surfavg",	"R_inferiortemporal_surfavg",	"R_isthmuscingulate_surfavg",	"R_lateraloccipital_surfavg",	"R_lateralorbitofrontal_surfavg",	"R_lingual_surfavg",	"R_medialorbitofrontal_surfavg",	"R_middletemporal_surfavg",	"R_parahippocampal_surfavg",	"R_paracentral_surfavg",	"R_parsopercularis_surfavg",	"R_parsorbitalis_surfavg",	"R_parstriangularis_surfavg",	"R_pericalcarine_surfavg",	"R_postcentral_surfavg",	"R_posteriorcingulate_surfavg",	"R_precentral_surfavg",	"R_precuneus_surfavg",	"R_rostralanteriorcingulate_surfavg",	"R_rostralmiddlefrontal_surfavg",	"R_superiorfrontal_surfavg",	"R_superiorparietal_surfavg",	"R_superiortemporal_surfavg",	"R_supramargil_surfavg",	"R_frontalpole_surfavg",	"R_temporalpole_surfavg",	"R_transversetemporal_surfavg",	"R_insula_surfavg",	"ICV",	"Site_enigma",	"Tesla",	"Scanner"]
categorical_variables = ["Sex"]
target_variable = "Exposed_YN"
has_header = true # First row of the dataset is a header with the name of each column
train = true
predict_new = false
get_results = true
time_limit = 2 # In hours
impute_method = "mean" # Either mean, median, most_frequent
standardize = true
n_runs = 2

[plots]
max_display_features = 50

[regression.regression_models]
linear_regression = true
gbm = true
xgBoost = true

[regression.performance_metrics]
rmse = true
mae = true
r_squared = true
pearson_correlation = true

[regression.regression_models.gbm_params]
learning_rate=[0.005,0.01]
n_estimators=[10,15,20]
min_samples_split=[500,1000]
min_samples_leaf=[10,20,30,40,50]
max_depth=[5,8]
max_features='sqrt'
subsample=[0.8]
model_selection_metric="mae"

[regression.regression_models.xgb_params]
learning_rate=[0.005,0.1]
max_depth=[10,15,20]
colsample_bytree=[0.3]
n_estimators=[10,20,30,40,50]
gamma=[0.01,0.1,1.0]
alpha=[1,10,20]
lambda=[0.001,0.01,0.1,1.0]
subsample=[0.8]
model_selection_metric="mae"

[classification.classification_models]
logistic_regression = false
extra_trees = false
random_forest = false
gbm = true
xgBoost = false

[classification.performance_metrics]
accuracy = true
balanced_accuracy = true
f1 = false
auc = false #performance measure for binary classification only, leave false otherwise
roc = false #performance measure for binary classification only, leave false otherwise

[classification.classification_models.ext_params]
n_estimators=[10,50,100,250,500,1000]
min_samples_split=[2,5,10,50,100]
min_samples_leaf=[1,5,10,25,50,100]
max_features='sqrt'
model_selection_metric="accuracy"

[classification.classification_models.rf_params]
n_estimators=[10,50,100,250,500,1000]
min_samples_split=[2,5,10,50,100]
min_samples_leaf=[1,5,10,25,50,100]
max_features='sqrt'
model_selection_metric="accuracy"

[classification.classification_models.gbm_params]
learning_rate=[0.0001, 0.005]
n_estimators=[10,50,100]
min_samples_split=[2,5]
min_samples_leaf=[5,10,20]
max_depth=[5,10,15,25]
max_features='sqrt'
subsample=[0.8]
model_selection_metric="balanced_accuracy"

[classification.classification_models.xgb_params]
learning_rate=[0.005,0.1]
max_depth=[10,15,20]
colsample_bytree=[0.3]
n_estimators=[10,20,30,40,50]
gamma=[0.01,0.1,1.0]
alpha=[1,10,20]
lambda=[0.001,0.01,0.1,1.0]
subsample=[0.8]
model_selection_metric="accuracy"
