title = "Configuration File"

[common_parameters]
problem_type = "regression"
train_val_split = 0.75 # 75% of samples in the training set, 25% in the validation Settings
variables = ["State","Border","Value"]
categorical_variables = ["State","Border"]
target_variable = "Value"
has_header = true # First row of the dataset is a header with the name of each column
train = true
predict = true
record = true
time_limit = 2 # In hours
impute_method = "mean" # Either mean, median, most_frequent

[regression.regression_models]
linear_regression = true
lightGBM = true
xgBoost = true

[regression.performance_metrics]
rmse = true
mae = true
r_squared = true
pearson_correlation = true

[classification.classification_models]
logistic_regression = true
lightGBM = true
xgBoost = true

[classification.performance_metrics]
accuracy = true
f1 = true
precision_recall = true
roc = true
